/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;

public class MyServlet implements Servlet {

    @Override
    public void init(ServletConfig config) throws ServletException {
    }

    @Override
    public ServletConfig getServletConfig() {
        return null;
    }

    @Override
    public void service(ServletRequest req,
                        ServletResponse res) throws ServletException, java.io.IOException {
        res.getWriter().println("----- hello world! ----\n hahahhahahhaha");
    }

    @Override
    public java.lang.String getServletInfo() {
        return null;
    }

    @Override
    public void destroy() {
    }

}