version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:
    tomcat:
      image: tomcat:9.0.27
      ports: 
        - 8080:8080
      volumes:
        - ./webapps:/usr/local/tomcat/webapps

#   mysql:
#     build:
#       context: ./mysql
#       args:
#         - MYSQL_VERSION=${MYSQL_VERSION}
#     environment:
#       - MYSQL_DATABASE=${MYSQL_DATABASE}
#       - MYSQL_USER=${MYSQL_USER}
#       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#       - TZ=UTC+8
#     volumes:
#       - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     networks:
#       - backend

#   redis:
#     build: ./redis
#     volumes:
#       - ${DATA_PATH_HOST}/redis:/data
#     ports:
#       - "6379:6379"
#     networks:
#       - backend
